General:
  allow_insecure_connections: false
  flaresolverr: ''
  max_file_name_length: 95
  max_folder_name_length: 60
  proxy: ''
  required_free_space: 5
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
  vi_mode: false
Rate_Limiting_Options:
  connection_timeout: 15
  download_attempts: 10
  download_delay: 0.5
  max_simultaneous_downloads: 15
  max_simultaneous_downloads_per_domain: 5
  rate_limit: 50
  read_timeout: 300
